services:
  mysql:
    image: mysql:8.0
    container_name: mysql-phishing
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phishing_db
      MYSQL_USER: phishing_user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - phishing-net

  backend:
    build: ./backend 
    container_name: backend-phishing
    restart: always
    ports:
      - "5000:5000" 
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: phishing_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: phishing_db
      MYSQL_PORT: 3306
      OPENAI_API_KEY: ${OPENAI_API_KEY} # Read from .env file on host
      SMTP_SERVER: "mailhog"
      SMTP_PORT: 1025
      BASE_URL: "http://localhost:5000"
      FLASK_DEBUG: 1 
    volumes:
      - ./backend:/app 
    depends_on:
      - mysql 
    networks:
      - phishing-net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-phishing
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - phishing-net

volumes:
  mysql-data: 

networks:
  phishing-net: 
    driver: bridge
